### ISSUE TITLE
U1 - Task 1 - Bootstrap CSS framework

### ISSUE THREAD

**Issue by CRROMO** [Morning-Leaf/mgt656-spring-2015-project#3]
As any user, I can visit your site and it looks awesome

**Comment by CRROMO** [comment]
Every page uses the Bootstrap CSS framework and therefore has some palatable defaults. You can include bootstrap from a CDN or serve it from your application.

```
Grading Note: the Bootstrap CSS should be included using a link element in the head with an href attribute that has the word "bootstrap" in it, like "bootstrap.css" or "bootstrap-min.css".
```

**Comment by metakool** [comment]
Listo!
